# Generated by Django 3.2.16 on 2022-12-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release_tracker", "0002_herokurelease_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="herokurelease",
            name="release_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="herokurelease",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
