# Generated by Django 4.1.4 on 2022-12-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release_tracker", "0004_herokurelease_release_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herokurelease",
            name="raw",
        ),
        migrations.AddField(
            model_name="herokurelease",
            name="github_release",
            field=models.JSONField(
                blank=True,
                help_text="Release as represented by the Github REST API.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="herokurelease",
            name="heroku_release",
            field=models.JSONField(
                blank=True,
                help_text="Release as represented by the Heroku platform API.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="herokurelease",
            name="pulled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the release was last pulled from Heroku",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="herokurelease",
            name="pushed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the release was last pushed to Github.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="herokurelease",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the release was created by Heroku.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="herokurelease",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Heroku release description (auto-generated).",
            ),
        ),
        migrations.AlterField(
            model_name="herokurelease",
            name="parent",
            field=models.OneToOneField(
                help_text="The previous release - used to generate changelog.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="release_tracker.herokurelease",
            ),
        ),
        migrations.AlterField(
            model_name="herokurelease",
            name="release_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The release note pulled from the Heroku platform API.",
            ),
        ),
    ]
