# Generated by Django 4.1.4 on 2022-12-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("release_tracker", "0005_remove_herokurelease_raw_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herokurelease",
            name="pulled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the release data was pulled from Heroku",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="herokurelease",
            name="pushed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the release data was pushed to Github.",
                null=True,
            ),
        ),
    ]
