# Generated by Django 3.2.16 on 2022-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HerokuRelease",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(unique=True)),
                ("description", models.TextField()),
                ("slug_id", models.UUIDField(blank=True, null=True)),
                ("commit_hash", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField()),
                ("raw", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(max_length=100)),
            ],
        ),
    ]
