# Generated by Django 3.2.16 on 2022-12-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroku_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="herokurelease",
            name="parent",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="heroku_app.herokurelease",
            ),
        ),
    ]
